apiVersion: v1
kind: Service
metadata:
  name: travel-agency
spec:
  selector:
    app: travel-agency
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency
spec:
  selector:
    matchLabels:
      app: travel-agency
  replicas: 1
  template:
    metadata:
      labels:
        app: travel-agency
    spec:
      containers:
        - name: server
          image: illiarahozin/travel-agency
          ports:
            - name: http
              containerPort: 8080

---